#Users

### GET User by ID
GET http://localhost:3000/api/v1/users/1
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXkiOm51bGwsIm1vYmlsZU51bWJlciI6NjM5MTcxMjM0NTY3LCJ0ZWxlcGhvbmUiOm51bGwsImVtYWlsIjoiYXpjLmJhbHRhemFyQGFya2NvbnN1bHQuY29tIiwic3RyZWV0IjpudWxsLCJjaXR5IjpudWxsLCJ6aXBDb2RlIjpudWxsfX0sImlhdCI6MTcyMTA0MTQxNywiZXhwIjoxNzIxMDQ1MDE3fQ.jsgkBPbyDpT-8dsECSSZmHQgTTJD9r234QiWSMvka78

### Create a new user
POST http://localhost:3000/api/v1/users/add
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXkiOm51bGwsIm1vYmlsZU51bWJlciI6NjM5MTcxMjM0NTY3LCJ0ZWxlcGhvbmUiOm51bGwsImVtYWlsIjoiYXpjLmJhbHRhemFyQGFya2NvbnN1bHQuY29tIiwic3RyZWV0IjpudWxsLCJjaXR5IjpudWxsLCJ6aXBDb2RlIjpudWxsfX0sImlhdCI6MTcyMTA0MTQxNywiZXhwIjoxNzIxMDQ1MDE3fQ.jsgkBPbyDpT-8dsECSSZmHQgTTJD9r234QiWSMvka78
content-type: application/json

{
    "firstName": "fritz",
    "lastName": "pambar",
    "email": "tdog.surreal@arkconsult.com",
    "mobileNumber": "09764556025",
    "role": "cashier"
}

### Update user by id
PATCH http://localhost:3000/api/v1/users/5
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXkiOm51bGwsIm1vYmlsZU51bWJlciI6NjM5MTcxMjM0NTY3LCJ0ZWxlcGhvbmUiOm51bGwsImVtYWlsIjoiYXpjLmJhbHRhemFyQGFya2NvbnN1bHQuY29tIiwic3RyZWV0IjpudWxsLCJjaXR5IjpudWxsLCJ6aXBDb2RlIjpudWxsfX0sImlhdCI6MTcyMTA0MTQxNywiZXhwIjoxNzIxMDQ1MDE3fQ.jsgkBPbyDpT-8dsECSSZmHQgTTJD9r234QiWSMvka78
Content-Type: application/json

{
  "firstName": "Daniza",
  "lastName": "Baltazar",
  "email": "azc.baltazar@arkconsult.com",
  "mobile": "+639171234567",
  "role": "admin",
  "status": "active",
  "zip_code": 12345,
  "city": "Makati",
  "street": "Ayala Avenue",
  "wageId": 1,
  "pin": 1234
}


### delete user by idDELETE http://localhost:3000/users/5
DELETE  http://localhost:3000/api/v1/users/1
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXkiOm51bGwsIm1vYmlsZU51bWJlciI6NjM5MTcxMjM0NTY3LCJ0ZWxlcGhvbmUiOm51bGwsImVtYWlsIjoiYXpjLmJhbHRhemFyQGFya2NvbnN1bHQuY29tIiwic3RyZWV0IjpudWxsLCJjaXR5IjpudWxsLCJ6aXBDb2RlIjpudWxsfX0sImlhdCI6MTcyMTA0MTQxNywiZXhwIjoxNzIxMDQ1MDE3fQ.jsgkBPbyDpT-8dsECSSZmHQgTTJD9r234QiWSMvka78


### Get user by email
GET http://localhost:3000/api/v1/users/email?email=abc@40test.com
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXki


### Get all users
GET http://localhost:3000/api/v1/users/user?username=daniza_baltazar&email=azc.baltazar@40arkconsult.com&period=today&status=active&role=admin&sortBy=createdAt&limit=10
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXkiOm51bGwsIm1vYmlsZU51bWJlciI6NjM5MTcxMjM0NTY3LCJ0ZWxlcGhvbmUiOm51bGwsImVtYWlsIjoiYXpjLmJhbHRhemFyQGFya2NvbnN1bHQuY29tIiwic3RyZWV0IjpudWxsLCJjaXR5IjpudWxsLCJ6aXBDb2RlIjpudWxsfX0sImlhdCI6MTcyMTA0MTQxNywiZXhwIjoxNzIxMDQ1MDE3fQ.jsgkBPbyDpT-8dsECSSZmHQgTTJD9r234QiWSMvka78


### Delete multiple users

DELETE http://localhost:3000/api/v1/users?ids=2,3
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXkiOm51bGwsIm1vYmlsZU51bWJlciI6NjM5MTcxMjM0NTY3LCJ0ZWxlcGhvbmUiOm51bGwsImVtYWlsIjoiYXpjLmJhbHRhemFyQGFya2NvbnN1bHQuY29tIiwic3RyZWV0IjpudWxsLCJjaXR5IjpudWxsLCJ6aXBDb2RlIjpudWxsfX0sImlhdCI6MTcyMTA0NTAwMSwiZXhwIjoxNzIxMDQ4NjAxfQ.Qwh8Jkqjcswmcg2RyBfisDQhnmGg-0lUI1gdsuzbNv0'

###Logout user


GET http://localhost:3000/api/v1/users/logout
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsicmVnaXN0cmF0aW9uVGltZXN0YW1wIjoiMjAyNC0wNy0xM1QxNzo0OTo1MS4wMDBaIiwibGFzdFVwZGF0ZVRpbWVzdGFtcCI6IjIwMjQtMDctMTNUMTc6NDk6NTEuMDAwWiIsImRlbGV0ZWRBdCI6bnVsbCwiaWQiOjEsInVzZXJuYW1lIjoiZGFuaXphX2JhbHRhemFyIiwid2FnZUlkIjpudWxsLCJyb2xlIjoiYWRtaW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJwaW4iOm51bGwsImdlbmVyYWxJbmZvIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJkYW5pemEiLCJsYXN0TmFtZSI6ImJhbHRhemFyIiwiYmlydGhkYXkiOm51bGwsIm1vYmlsZU51bWJlciI6NjM5MTcxMjM0NTY3LCJ0ZWxlcGhvbmUiOm51bGwsImVtYWlsIjoiYXpjLmJhbHRhemFyQGFya2NvbnN1bHQuY29tIiwic3RyZWV0IjpudWxsLCJjaXR5IjpudWxsLCJ6aXBDb2RlIjpudWxsfX0sImlhdCI6MTcyMTA0MTQxNywiZXhwIjoxNzIxMDQ1MDE3fQ.jsgkBPbyDpT-8dsECSSZmHQgTTJD9r234QiWSMvka78'
