export const urlsConstant = {
	API_PREFIX_V1: "/api/v1",

	ROUTE_PREFIX_AUTH: "/auth",
	API_SIGNUP_AUTH: "/signup",
	API_LOGIN_AUTH: "/login",
	API_LOGOUT_AUTH: "/logout",
	API_TOKEN_AUTH: "/token",
	API_WHOAMI_AUTH: "/whoami",

	ROUTE_PREFIX_CUSTOMER: "/customers",
	API_GET_CUSTOMER: "/:customerId",
	API_UPDATE_CUSTOMER: "/:customerId",
	API_DELETE_CUSTOMER: "/:customerId",
	API_DELETE_CUSTOMERS: "/delete-many",

	ROUTE_PREFIX_CATEGORY: "/categories",
	API_UPDATE_CATEGORY: "/:categoryId",
	API_DELETE_CATEGORY: "/:categoryId",

	ROUTE_PREFIX_BREAK: "/breaks",
	API_UPDATE_BREAK: "/:breakId",
	API_DELETE_BREAK: "/:breakId",

	ROUTE_PREFIX_WAGE: "/wages",
	API_UPDATE_WAGE: "/:wageId",
	API_DELETE_WAGE: "/:wageId",

	ROUTE_PREFIX_PRODUCT: "/products",
	API_GET_PRODUCT: "/:productId",
	API_UPDATE_PRODUCT: "/:productId",
	API_DELETE_PRODUCT: "/:productId",

	ROUTE_PREFIX_TRANSACTION: "/transactions",
	API_GET_TRANSACTION: "/:transactionId",
	API_UPDATE_TRANSACTION: "/:transactionId",
	API_UPDATE_TRANSACTION_ITEM: "/:transactionId/items/:itemId",
	API_DELETE_TRANSACTION: "/:transactionId",
	API_DELETE_TRANSACTIONS: "/delete-many",

	ROUTE_PREFIX_ATTENDANCE: "/attendances",
	API_GET_ATTENDANCE: "/:attendanceId",
	API_GET_ATTENDANCE_USER: "/:attendanceId/users",
	API_GET_ATTENDANCE_WAGE: "/:attendanceId/wages",
	API_GET_ATTENDANCE_BREAK: "/:attendanceId/break",
	API_UPDATE_ATTENDANCE: "/:attendanceId",
	API_DELETE_ATTENDANCE: "/:attendanceId",

	ROUTE_PREFIX_CASH_DRAWER: "/cash-drawers",
	API_GET_REGISTER: "/:registerId",
	API_UPDATE_REGISTER: "/:registerId",
	API_ADD_CASH_MANAGEMENT: "/:registerId/cash",
	API_EDIT_CASH_MANAGEMENT: "/:registerId/cash/:cashManagementId",

	ROUTE_PREFIX_USER: "/users",
	API_GET_USER_ID: "/:userId",
	API_GET_USER_EMAIL: "/email",
	API_UPDATE_USER: "/:userId",
	API_DELETE_USER: "/:userId",
	API_DELETE_USERS: "/delete-many",

	ROUTE_PREFIX_SUPPLIER: "/suppliers",
	API_GET_SUPPLIER: "/:supplierId",
	API_GET_SUPPLIERS_SUMMARY: "/summary",
	API_UPDATE_SUPPLIER: "/:supplierId",
	API_DELETE_SUPPLIER: "/:supplierId",
	API_DELETE_SUPPLIERS: "/delete-many",

	ROUTE_PREFIX_DISCOUNT: "/discounts",
	API_GET_DISCOUNT: "/:discountId",
	API_GET_DISCOUNTS_STORE: "/stores/:storeId",
	API_GET_DISCOUNTS_CHECK: "/check",
	API_GET_DISCOUNTS_TRANSACTION: "/transaction",
	API_GET_DISCOUNTS_TRANSACTION_SUMMARY: "/transaction/summary",
	API_GET_DISCOUNTS_TRANSACTION_SUMMARY_ID: "/transaction/summary/:discountId",
	API_UPDATE_DISCOUNT: "/:discountId",
	API_DELETE_DISCOUNT: "/:discountId",
	API_DELETE_DISCOUNTS: "/delete-many",

	ROUTE_PREFIX_INVENTORY: "/inventories",
	API_GET_INVENTORY: "/:inventoryId",
	API_UPDATE_INVENTORY: "/:inventoryId",
	API_DELETE_INVENTORY: "/:inventoryId",
	API_DELETE_INVENTORIES: "/delete-many",
	API_FILTER_INVENTORY: "/filter",

	ROUTE_PREFIX_PURCHASES: "/purchases",
	API_UPDATE_PURCHASE: "/:purchaseId",
	API_DELETE_PURCHASE: "/:purchaseId",
	API_DELETE_PURCHASES: "/delete-many",

	ROUTE_PREFIX_MODIFIER: "/modifiers",
	API_UPDATE_MODIFIER: "/:modifierId",
	API_DELETE_MODIFIER: "/:modifierId",
	API_GET_MODIFIER: "/:modifierId",

	ROUTE_PREFIX_ACCOUNTING_ANALYTICS: "/analytics/accounting",
	API_GET_ACCOUNTING_DAILY_SUMMARY: "/daily-summary",
	API_GET_ACCOUNTING_ALL_TRANSACTIONS: "/all-transactions",

	ROUTE_PREFIX_DISCOUNT_ANALYTICS: "/analytics/sales",
	API_GET_ANALYTICS_DISCOUNT_SUMMARY: "/discount-summary",
	API_GET_ANALYTICS_DISCOUNT_TRANSACTION: "/discount-transactions",
	API_GET_ANALYTICS_REFUND_TRANSACTION: "/refunded-transactions",
	API_GET_ANALYTICS_FAILED_TRANSACTION: "/failed-transactions",
	API_GET_ANALYTICS_REVENUE: "/revenue-transactions",
	API_GET_ANALYTICS_END_OF_DAY: "/end-of-day-transactions",
	API_GET_ANALYTICS_AVERAGE_ORDER: "/average-order-transactions",
	API_GET_ANALYTICS_DAY_OF_WEEK: "/day-of-week-transactions",
	API_GET_SALES_TIME_OF_DAY: "/time-of-day",
	API_GET_SALES_PRODUCTS: "/products",
	API_GET_SALES_CATEGORIES: "/categories",
	API_GET_SALES_TIPS_BY_DAY: "/tips-by-day",

	ROUTE_PREFIX_REGISTER_ANALYTICS: "/analytics/register",
	API_GET_ANALYTICS_REGISTER_SUMMARY: "/register-summary",

	ROUTE_PREFIX_REFUND: "/refunds",

	ROUTE_PREFIX_DASHBOARD_ANALYTICS: "/dashboard-analytics",
	API_GET_DASHBOARD_SALES_SUMMARY: "/sales-summary",
	API_GET_DASHBOARD_TOTAL_SALES: "/total-sales",
	API_GET_DASHBOARD_PRODUCT_SALES: "/product-sales",
	API_GET_DASHBOARD_COMPARE_STORES: "/compare-stores",
	API_GET_BEST_SELLERS: "/best-sellers",
};
