### GET discount summary
GET http://127.0.0.1:3000/api/v1/analytics/sales/discount-summary?page=1&limit=10&fromDate=2024-01-01&toDate=2024-12-01&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsiY3JlYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwiZGVsZXRlZEF0IjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJkYW5pemFfYmFsdGF6YXJ4eHh4eCIsIndhZ2VJZCI6bnVsbCwicm9sZSI6ImFkbWluIiwic3RhdHVzIjoiYWN0aXZlIiwicGluIjpudWxsLCJjb250YWN0SW5mbyI6bnVsbH0sImlhdCI6MTcyMzk2ODA4OCwiZXhwIjoxNzIzOTcxNjg4fQ.-jvbnURhqnAzawFAEdzn1pDurAGsbNqyjerPwSh0eTM

### GET discount transaction
GET http://127.0.0.1:3000/api/v1/analytics/sales/discount-transactions?page=1&limit=10&fromDate=2024-01-01&toDate=2024-12-01&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsiY3JlYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwiZGVsZXRlZEF0IjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJkYW5pemFfYmFsdGF6YXJ4eHh4eCIsIndhZ2VJZCI6bnVsbCwicm9sZSI6ImFkbWluIiwic3RhdHVzIjoiYWN0aXZlIiwicGluIjpudWxsLCJjb250YWN0SW5mbyI6bnVsbH0sImlhdCI6MTcyMzk2ODA4OCwiZXhwIjoxNzIzOTcxNjg4fQ.-jvbnURhqnAzawFAEdzn1pDurAGsbNqyjerPwSh0eTM

### GET refund transaction
GET http://127.0.0.1:3000/api/v1/analytics/sales/refunded-transactions?page=1&limit=10&fromDate=2024-01-01&toDate=2024-10-01&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsiY3JlYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwiZGVsZXRlZEF0IjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJkYW5pemFfYmFsdGF6YXJ4eHh4eCIsIndhZ2VJZCI6bnVsbCwicm9sZSI6ImFkbWluIiwic3RhdHVzIjoiYWN0aXZlIiwicGluIjpudWxsLCJjb250YWN0SW5mbyI6bnVsbH0sImlhdCI6MTcyMzk2ODA4OCwiZXhwIjoxNzIzOTcxNjg4fQ.-jvbnURhqnAzawFAEdzn1pDurAGsbNqyjerPwSh0eTM

### GET failed transaction
GET http://127.0.0.1:3000/api/v1/analytics/sales/failed-transactions?page=1&limit=10&fromDate=2024-01-01&toDate=2024-10-01&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsiY3JlYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwiZGVsZXRlZEF0IjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJkYW5pemFfYmFsdGF6YXJ4eHh4eCIsIndhZ2VJZCI6bnVsbCwicm9sZSI6ImFkbWluIiwic3RhdHVzIjoiYWN0aXZlIiwicGluIjpudWxsLCJjb250YWN0SW5mbyI6bnVsbH0sImlhdCI6MTcyMzk2ODA4OCwiZXhwIjoxNzIzOTcxNjg4fQ.-jvbnURhqnAzawFAEdzn1pDurAGsbNqyjerPwSh0eTM

### GET revenue transaction
GET http://127.0.0.1:3000/api/v1/analytics/sales/revenue-transactions?page=1&limit=10&fromDate=2024-01-01&toDate=2024-10-01&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsiY3JlYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwiZGVsZXRlZEF0IjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJkYW5pemFfYmFsdGF6YXJ4eHh4eCIsIndhZ2VJZCI6bnVsbCwicm9sZSI6ImFkbWluIiwic3RhdHVzIjoiYWN0aXZlIiwicGluIjpudWxsLCJjb250YWN0SW5mbyI6bnVsbH0sImlhdCI6MTcyMzk2ODA4OCwiZXhwIjoxNzIzOTcxNjg4fQ.-jvbnURhqnAzawFAEdzn1pDurAGsbNqyjerPwSh0eTM

### GET end of day transaction
GET http://127.0.0.1:3000/api/v1/analytics/sales/end-of-day-transactions?page=1&limit=10&fromDate=2024-01-01&toDate=2024-10-01&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsiY3JlYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwiZGVsZXRlZEF0IjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJkYW5pemFfYmFsdGF6YXJ4eHh4eCIsIndhZ2VJZCI6bnVsbCwicm9sZSI6ImFkbWluIiwic3RhdHVzIjoiYWN0aXZlIiwicGluIjpudWxsLCJjb250YWN0SW5mbyI6bnVsbH0sImlhdCI6MTcyMzk2ODA4OCwiZXhwIjoxNzIzOTcxNjg4fQ.-jvbnURhqnAzawFAEdzn1pDurAGsbNqyjerPwSh0eTM

### GET average order transaction
GET http://127.0.0.1:3000/api/v1/analytics/sales/average-order-transactions?page=1&limit=10&fromDate=2024-01-01&toDate=2024-10-01&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvYmplY3QiOnsiY3JlYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wOC0xNFQwMDo1ODowNC4wMDBaIiwiZGVsZXRlZEF0IjpudWxsLCJpZCI6MSwidXNlcm5hbWUiOiJkYW5pemFfYmFsdGF6YXJ4eHh4eCIsIndhZ2VJZCI6bnVsbCwicm9sZSI6ImFkbWluIiwic3RhdHVzIjoiYWN0aXZlIiwicGluIjpudWxsLCJjb250YWN0SW5mbyI6bnVsbH0sImlhdCI6MTcyMzk2ODA4OCwiZXhwIjoxNzIzOTcxNjg4fQ.-jvbnURhqnAzawFAEdzn1pDurAGsbNqyjerPwSh0eTM